### ISSUE TITLE
Ironwolf Pro drives not recognized

### ISSUE THREAD

**Issue by Gex2501** [gamestailer94/farm-check#15]
Some of my drives show SMART and FARM data but nothing else, these are my Ironwolf Pro drives. Here is some sample output as well as a full log. I'm using the docker container. It's probably of no consequence but would be nice to see the same info as the other Ironwolves

```
=== Checking device: /dev/sdd ===

SMART: 14816
FARM: 14816
RESULT: PASS

=== Checking device: /dev/sde ===
Model Family:     Western Digital Red
Device Model:     WDC WD60EFRX-68L0BN1
Serial Number:    WD-WX31D27N8R5R
FARM data not available - likely not a Seagate drive
SMART: 32378
FARM: N/A
RESULT: SKIP

=== Checking device: /dev/sdf ===
Model Family:     Seagate IronWolf
Device Model:     ST8000VN004-2M2101
Serial Number:    WKD1W98K
SMART: 39507
FARM: 39507
RESULT: PASS
```

[FARM-check.log](https://github.com/user-attachments/files/19062064/FARM-check.log)

**Comment by chjohans** [comment]
I see the same issue. Just replaced a FARM used driver with a new Ironwolf Pro 12TB, and I see exactly the same as above.  This is a genuine IronWolf Pro 12TB, ST12000NT001, product number 3LX101-500, firmware EN01.

**Comment by TheRealDevKat** [comment]
The way the device information were pulled was limited to the correct reporting of Model Family, which not all drives do. This has now been fixed in the new version.

**Comment by chjohans** [comment]
It's still not working for me, but I'm using this in Docker on my Synology NAS, and maybe the latest Docker image has not been updated with this fix yet?

**Comment by TheRealDevKat** [comment]
Have you pulled the newest image ?
The Image gets automatically updated with each new commit

**Comment by chjohans** [comment]
I'm running "docker run --rm --privileged -v /dev:/dev ghcr.io/gamestailer94/farm-check:latest ALL" and I thought that would automatically pull the latest image, but I'll manually pull the image just in case

**Comment by TheRealDevKat** [comment]
That command only pulls the image if it's not already stored locally, so only once. If you want to update, you need to manually pull with `docker pull ghcr.io/gamestailer94/farm-check:latest`

**Comment by chjohans** [comment]
I'm running this on a Synology NAS, and their "Container manager" (docker GUI) claimed I had the latest version. And when running  "docker run --rm --privileged -v /dev:/dev ghcr.io/gamestailer94/farm-check:latest ALL"  it didn't pull a new image.

Are you sure you are tagging your latest image with "latest"?
 
Anyhow, I just deleted the image and it pulled the latest image, but my newly installed IronWolf Pro 12TB is still now reporting it as such:

 === Checking device: /dev/sata3 ===
Model Family:   N/A (smartmontools does not know this device or the device does not report Model Family)
Device Model:   ST12000NT001-3LX101
Serial Number:  ZRT2BKZ2

SMART:          33
FARM:           33
RESULT:         PASS

Not really a big deal as the FARM log values are still being read correctly.

Oh, and thanks a lot for putting together this tool. I successfully used it to find two drives that had been sold to me as new, but were indeed two of those drives that had their SMART data reset.

**Comment by chjohans** [comment]
> That command only pulls the image if it's not already stored locally, so only once. If you want to update, you need to manually pull with `docker pull ghcr.io/gamestailer94/farm-check:latest`

Yeah, that's what I found out too. I always thought that when running the image with the ":lversioN" flag it would check and pull the correct image. Now I know better! :)

**Comment by TheRealDevKat** [comment]
The script does what it's supposed to do
```
Model Family: N/A (smartmontools does not know this device or the device does not report Model Family)
```
The N/A Message is new, and the best I could do (because, as stated, the drives does not report its family), at least you get the serial and model number now.

**Comment by chjohans** [comment]
Yup, it's fine as it is, it's reporting what is important! :)

**Comment by Gex2501** [comment]
Thanks very much! This tool is really helpful!
